# The largest heading
## This site was built using [GitHub Pages](https://pages.github.com/).

## About me

Hi, I'm Mona. You might recognize me as GitHub's mascot.

| Rank | Languages |
|-----:|-----------|
|     1| Javascript|
|     2| Python    |
|     3| SQL       |

> Text that is a quote

Some basic Git commands are:
```
git status
git add
git commit
```

The background color should be `#ffffff` for light mode and `#0d1117` for dark mode.

![This is an image](https://myoctocat.com/assets/images/base-octocat.svg)
